import { readFileSync, writeFileSync } from 'fs'
let a = readFileSync('src/components/About.jsx', 'utf8')
a = a.replace("const { about } = config.content", "const { about } = config.content\nconst { yearsExperience } = config.business")
a = a.replace('[X]+</span>', '{yearsExperience}+</span>')
a = a.replace('[X]+ Years of Experience', '{yearsExperience}+ Years of Experience')
writeFileSync('src/components/About.jsx', a, 'utf8')
console.log('1. About.jsx fixed')
let css = readFileSync('src/components/TrustBar.css', 'utf8')
css = css.replace('repeat(5, 1fr)', 'repeat(4, 1fr)')
writeFileSync('src/components/TrustBar.css', css, 'utf8')
console.log('2. TrustBar grid fixed')
let c = readFileSync('src/config.js', 'utf8')
c = c.replace('reviewCount: "50+"', 'reviewCount: "27"')
writeFileSync('src/config.js', c, 'utf8')
console.log('3. Review count set to 27')
